language: java
jdk:
# JMockit problem JDK > 8  
  - openjdk14
  - openjdk13
  - openjdk12
  - openjdk11
  - oraclejdk9
  - oraclejdk11
  - openjdk10
  - openjdk8

script: ant testsuiteLinux

before_install:
#    - "JAVA_VER=$(java -version 2>&1 | sed -n ';s/.* version "\(.*\)\.\(.*\)\..*"/\1\2/p;')"
#    - "echo $JAVA_VER"
#    - "[$JAVA_VER -le 18] && sudo cp application_data/jce_policy/java7/*.jar $JAVA_HOME/jre/lib/security"
#    - "ls -la $JAVA_HOME/jre/lib/security"
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
after_failure: "cat test/report/TEST-ataraxis.AtaraxisTestSuite.xml"
